export const forgeableAuctionItems: string[] = [
  "Mithril Pickaxe",
  "Beacon II",
  "Titanium Talisman",
  "Bejeweled Collar",
  "Mithril Gauntlet",
  "Mithril Belt",
  "Mithril Cloak",
  "Mithril Necklace",
  "Chisel",
  "Refined Mithril Pickaxe",
  "Mithril Drill SX-R226",
  "Mithril-Infused Fuel Tank",
  "Mithril-Plated Drill Engine",
  "Beacon III",
  "Titanium Ring",
  "Pesto Goblin Omelette",
  "[Lvl 1] Ammonite",
  "Ruby Drill TX-15",
  "Titanium Gauntlet",
  "Titanium Belt",
  "Titanium Cloak",
  "Titanium Necklace",
  "[Lvl 1] Mole",
  "Mithril Drill SX-R326",
  "Titanium-Plated Drill Engine",
  "Goblin Omelette",
  "Beacon IV",
  "Sunny Side Goblin Omelette",
  "Gemstone Drill LT-522",
  "Titanium Drill DR-X355",
  "Titanium Drill DR-X455",
  "Titanium Drill DR-X555",
  "Titanium-Infused Fuel Tank",
  "Beacon V",
  "Titanium Artifact",
  "Titanium Relic",
  "Spicy Goblin Omelette",
  "Gemstone Chamber",
  "Topaz Drill KGR-12",
  "Ruby-Polished Drill Engine",
  "Gemstone Fuel Tank",
  "Amethyst Gauntlet",
  "Jade Belt",
  "Sapphire Cloak",
  "Amber Necklace",
  "Blue Cheese Goblin Omelette",
  "Titanium Drill DR-X655",
  "Jasper Drill X",
  "Sapphire-Polished Drill Engine",
  "Helmet of Divan",
  "Chestplate of Divan",
  "Leggings of Divan",
  "Boots of Divan",
  "Amber-Polished Drill Engine",
  "Perfectly-Cut Fuel Tank",
  "Divan's Drill",
  "[Lvl 1] T-Rex",
  "[Lvl 1] Spinosaurus",
  "[Lvl 1] Goblin",
  "[Lvl 1] Ankylosaurus",
  "[Lvl 1] Penguin",
  "[Lvl 1] Mammoth",
  "Dwarven Handwarmers",
  "Reinforced Chisel",
  "Dwarven Metal Talisman",
  "Portable Campfire",
  "Tungsten Regulator",
  "Glacite-Plated Chisel",
  "Perfect Chisel",
  "Pendant of Divan",
  "Relic of Power",
];

export const forgeablePets: string[] = [
  "[Lvl 1] Ammonite",
  "[Lvl 1] Mole",
  "[Lvl 1] T-Rex",
  "[Lvl 1] Spinosaurus",
  "[Lvl 1] Goblin",
  "[Lvl 1] Ankylosaurus",
  "[Lvl 1] Penguin",
  "[Lvl 1] Mammoth",
];

export const forgeableTools: string[] = [
  "Mithril Pickaxe",
  "Refined Mithril Pickaxe",
  "Mithril Drill SX-R226",
  "Ruby Drill TX-15",
  "Mithril Drill SX-R326",
  "Gemstone Drill LT-522",
  "Titanium Drill DR-X355",
  "Titanium Drill DR-X455",
  "Titanium Drill DR-X555",
  "Topaz Drill KGR-12",
  "Titanium Drill DR-X655",
  "Jasper Drill X",
  "Divan's Drill",
];

export const forgeableBazaarItems: string[] = [
  "Refined Diamond",
  "Refined Mithril",
  "Refined Titanium",
  "Refined Tungsten",
  "Refined Umber",
  "Fuel Canister",
  "Bejeweled Handle",
  "Drill Motor",
  "Golden Plate",
  "Mithril Plate",
  "Tungsten Plate",
  "Umber Plate",
  "Gemstone Mixture",
  "Glacite Amalgamation",
  "Perfect Jasper Gemstone",
  "Perfect Ruby Gemstone",
  "Perfect Jade Gemstone",
  "Perfect Sapphire Gemstone",
  "Perfect Amber Gemstone",
  "Perfect Topaz Gemstone",
  "Perfect Amethyst Gemstone",
  "Perfect Opal Gemstone",
  "Perfect Onyx Gemstone",
  "Perfect Citrine Gemstone",
  "Perfect Aquamarine Gemstone",
  "Perfect Peridot Gemstone",
  "Perfect Plate",
  "Diamonite",
  "Pocket Iceberg",
  "Power Crystal",
  "Tungsten Key",
  "Umber Key",
  "Frigid Husk",
  "Pure Mithril",
  "Titanium Tesseract",
  "Dwarven Geode",
  "Petrified Starfall",
  "Scorched Topaz",
  "Gleaming Crystal",
  "Amber Material",
  "Divan's Powder Coating",
  "Skeleton Key",
];

export const forgeableGemstones: string[] = [
  "Perfect Jasper Gemstone",
  "Perfect Ruby Gemstone",
  "Perfect Jade Gemstone",
  "Perfect Sapphire Gemstone",
  "Perfect Amber Gemstone",
  "Perfect Topaz Gemstone",
  "Perfect Amethyst Gemstone",
  "Perfect Opal Gemstone",
  "Perfect Onyx Gemstone",
  "Perfect Citrine Gemstone",
  "Perfect Aquamarine Gemstone",
  "Perfect Peridot Gemstone",
];

export const forgeableReforges: string[] = [
  "Diamonite",
  "Pocket Iceberg",
  "Frigid Husk",
  "Pure Mithril",
  "Titanium Tesseract",
  "Dwarven Geode",
  "Petrified Starfall",
  "Scorched Topaz",
  "Gleaming Crystal",
  "Amber Material",
];
