export const forgeableAuctionItems: string[] = [
  'Mithril Pickaxe',
  'Beacon II',
  'Titanium Talisman',
  'Bejeweled Collar',
  'Mithril Gauntlet',
  'Mithril Belt',
  'Mithril Cloak',
  'Mithril Necklace',
  'Chisel',
  'Refined Mithril Pickaxe',
  'Mithril Drill SX-R226',
  'Mithril-Infused Fuel Tank',
  'Mithril-Plated Drill Engine',
  'Beacon III',
  'Titanium Ring',
  'Pesto Goblin Omelette',
  'Ammonite Pet',
  'Ruby Drill TX-15',
  'Titanium Gauntlet',
  'Titanium Belt',
  'Titanium Cloak',
  'Titanium Necklace',
  'Mole Pet',
  'Mithril Drill SX-R326',
  'Titanium-Plated Drill Engine',
  'Goblin Omelette',
  'Beacon IV',
  'Sunny Side Goblin Omelette',
  'Gemstone Drill LT-522',
  'Titanium Drill DR-X355',
  'Titanium Drill DR-X455',
  'Titanium Drill DR-X555',
  'Titanium-Infused Fuel Tank',
  'Beacon V',
  'Titanium Artifact',
  'Titanium Relic',
  'Spicy Goblin Omelette',
  'Gemstone Chamber',
  'Topaz Drill KGR-12',
  'Ruby-Polished Drill Engine',
  'Gemstone Fuel Tank',
  'Amethyst Gauntlet',
  'Jade Belt',
  'Sapphire Cloak',
  'Amber Necklace',
  'Blue Cheese Goblin Omelette',
  'Titanium Drill DR-X655',
  'Jasper Drill X',
  'Sapphire-Polished Drill Engine',
  'Helmet of Divan',
  'Chestplate of Divan',
  'Leggings of Divan',
  'Boots of Divan',
  'Amber-Polished Drill Engine',
  'Perfectly-Cut Fuel Tank',
  "Divan's Drill",
  'T-Rex Pet',
  'Spinosaurus Pet',
  'Goblin Pet',
  'Ankylosaurus Pet',
  'Penguin Pet',
  'Mammoth Pet',
  'Dwarven Handwarmers',
  'Reinforced Chisel',
  'Dwarven Metal Talisman',
  'Portable Campfire',
  'Tungsten Regulator',
  'Glacite-Plated Chisel',
  'Perfect Chisel',
  'Pendant of Divan',
  'Relic of Power',
];

export const forgeablePets: string[] = [
  'Ammonite Pet',
  'Mole Pet',
  'T-Rex Pet',
  'Spinosaurus Pet',
  'Goblin Pet',
  'Ankylosaurus Pet',
  'Penguin Pet',
  'Mammoth Pet',
];

export const forgeableTools: string[] = [
  'Mithril Pickaxe',
  'Refined Mithril Pickaxe',
  'Mithril Drill SX-R226',
  'Ruby Drill TX-15',
  'Mithril Drill SX-R326',
  'Gemstone Drill LT-522',
  'Titanium Drill DR-X355',
  'Titanium Drill DR-X455',
  'Titanium Drill DR-X555',
  'Topaz Drill KGR-12',
  'Titanium Drill DR-X655',
  'Jasper Drill X',
  "Divan's Drill",
];

export const forgeableBazaarItems: string[] = [
  'Refined Diamond',
  'Refined Mithril',
  'Refined Titanium',
  'Refined Tungsten',
  'Refined Umber',
  'Fuel Canister',
  'Bejeweled Handle',
  'Drill Motor',
  'Golden Plate',
  'Mithril Plate',
  'Tungsten Plate',
  'Umber Plate',
  'Gemstone Mixture',
  'Glacite Amalgamation',
  'Perfect Jasper Gemstone',
  'Perfect Ruby Gemstone',
  'Perfect Jade Gemstone',
  'Perfect Sapphire Gemstone',
  'Perfect Amber Gemstone',
  'Perfect Topaz Gemstone',
  'Perfect Amethyst Gemstone',
  'Perfect Opal Gemstone',
  'Perfect Onyx Gemstone',
  'Perfect Citrine Gemstone',
  'Perfect Aquamarine Gemstone',
  'Perfect Peridot Gemstone',
  'Perfect Plate',
  'Diamonite',
  'Pocket Iceberg',
  'Power Crystal',
  'Tungsten Key',
  'Umber Key',
  'Frigid Husk',
  'Pure Mithril',
  'Titanium Tesseract',
  'Dwarven Geode',
  'Petrified Starfall',
  'Scorched Topaz',
  'Gleaming Crystal',
  'Amber Material',
  "Divan's Powder Coating",
  'Skeleton Key',
];

export const forgeableGemstones: string[] = [
  'Perfect Jasper Gemstone',
  'Perfect Ruby Gemstone',
  'Perfect Jade Gemstone',
  'Perfect Sapphire Gemstone',
  'Perfect Amber Gemstone',
  'Perfect Topaz Gemstone',
  'Perfect Amethyst Gemstone',
  'Perfect Opal Gemstone',
  'Perfect Onyx Gemstone',
  'Perfect Citrine Gemstone',
  'Perfect Aquamarine Gemstone',
  'Perfect Peridot Gemstone',
];

export const forgeableReforges: string[] = [
  'Diamonite',
  'Pocket Iceberg',
  'Frigid Husk',
  'Pure Mithril',
  'Titanium Tesseract',
  'Dwarven Geode',
  'Petrified Starfall',
  'Scorched Topaz',
  'Gleaming Crystal',
  'Amber Material',
];

export const auctionItemLBINs: { [displayName: string]: number | null } = {
  'Beacon I': null,
  'Beacon II': null,
  'Titanium Talisman': null,
  'Helix Fossil': null,
  'Mithril Gauntlet': null,
  'Mithril Belt': null,
  'Mithril Cloak': null,
  'Mithril Necklace': null,
  'Claw Fossil': null,
  'Mithril Drill SX-R226': null,
  'Beacon III': null,
  'Titanium Ring': null,
  'Ruby Drill TX-15': null,
  'Titanium Drill DR-X355': null,
  'Titanium Drill DR-X455': null,
  'Titanium Drill DR-X555': null,
  'Mithril-Infused Fuel Tank': null,
  'Beacon IV': null,
  'Titanium Artifact': null,
  'Gemstone Drill LT-522': null,
  'Titanium-Infused Fuel Tank': null,
  'Topaz Drill KGR-12': null,
  'Mithril-Plated Drill Engine': null,
  'Titanium-Plated Drill Engine': null,
  'Sapphire-Polished Drill Engine': null,
  'Ruby-Polished Drill Engine': null,
  'Gemstone Fuel Tank': null,
  "Divan's Alloy": null,
  'Titanium Drill DR-X655': null,
  'Footprint Fossil': null,
  'Spine Fossil': null,
  'Ugly Fossil': null,
  'Clubbed Fossil': null,
  'Webbed Fossil': null,
  'Tusk Fossil': null,
  Chisel: null,
  'Reinforced Chisel': null,
  'Glacite-Plated Chisel': null,
  'Shattered Locket': null,
  'Artifact Of Power': null,
  'Mithril Pickaxe': null,
  'Bejeweled Collar': null,
  'Refined Mithril Pickaxe': null,
  'Pesto Goblin Omelette': null,
  'Ammonite Pet': null,
  'Titanium Gauntlet': null,
  'Titanium Belt': null,
  'Titanium Cloak': null,
  'Titanium Necklace': null,
  'Mole Pet': null,
  'Mithril Drill SX-R326': null,
  'Goblin Omelette': null,
  'Sunny Side Goblin Omelette': null,
  'Beacon V': null,
  'Titanium Relic': null,
  'Spicy Goblin Omelette': null,
  'Gemstone Chamber': null,
  'Amethyst Gauntlet': null,
  'Jade Belt': null,
  'Sapphire Cloak': null,
  'Amber Necklace': null,
  'Blue Cheese Goblin Omelette': null,
  'Jasper Drill X': null,
  'Helmet of Divan': null,
  'Chestplate of Divan': null,
  'Leggings of Divan': null,
  'Boots of Divan': null,
  'Amber-Polished Drill Engine': null,
  'Perfectly-Cut Fuel Tank': null,
  "Divan's Drill": null,
  'T-Rex Pet': null,
  'Mammoth Pet': null,
  'Spinosaurus Pet': null,
  'Penguin Pet': null,
  'Goblin Pet': null,
  'Ankylosaurus Pet': null,
  'Dwarven Handwarmers': null,
  'Perfect Chisel': null,
  'Dwarven Metal Talisman': null,
  'Portable Campfire': null,
  'Tungsten Regulator': null,
  'Pendant of Divan': null,
  'Relic of Power': null,
};
